spring:
  application:
    name: Shoes-Market

  datasource:
    url: jdbc:mysql://localhost:3306/shoes_market?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  liquibase:
    change-log: classpath:/db/changelog.xml

logging:
  level:
    root: INFO
  file:
    name: log\\application.log

jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
  expiration: 600000