spring:
  application:
    name: Shoes-Market

  datasource:
    url: jdbc:mysql://localhost:3306/shoes_market?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  liquibase:
    change-log: classpath:/db/changelog.xml

logging:
  level:
    root: INFO
  file:
    name: log\\application.log

user:
  image:
    uploadPath: userImage\